# Try Catch

```php

// similar al do-while
try { // ejecuta este codigo:

    /* codigo... */

    throw new Exception('exception personalizada'); // opcional

/*                  üëá puede ser cualquier nombre */
} catch (Exeption $exception) { // si te d√° error...
// ... aqu√≠ lo que quieras hacer en caso de error. 
// aclaracion: pueden haber varios catch

    /* explicacion */

    $exeption.getMessage()         /* Obtiene el mensaje de Excepci√≥n. Se usa en el ejemplo anterior*/

    $exeption.getPrevious()        /* Devuelve la excepci√≥n anterior.*/

    $exeption.getCode()            /* Obtiene el c√≥digo de Excepci√≥n. Este m√©todo es √∫til para a√±adir en el log de errores.*/

    $exeption.getFile()            /* Obtiene el fichero en el que ocurri√≥ la excepci√≥n. Este m√©todo es √∫til para a√±adir en el log de errores.*/

    $exeption.getLine()            /* Obtiene la l√≠nea en donde ocurri√≥ la excepci√≥n. Este m√©todo es √∫til para a√±adir en el log de errores.*/

    $exeption.getTrace()          /*Obtiene el seguimiento de la pila. Este m√©todo es √∫til para a√±adir en el log de errores.*/

    $exeption.getTraceAsString()  /*Obtiene el stack trace como cadena.*/

    /* codigo... */

    die("Error: ",$exeption.getMessage()) // die = console.log + break

}finally{ /* Finally:Este bloque siempre se ejecutar√° 
independientemente de que se haya lanzado una excepci√≥n o no, 
y antes de que la ejecuci√≥n normal contin√∫e. No es obligatorio. */

    /* codigo... */


}

```